### ISSUE TITLE
Fix being stuck in between the platforms

### ISSUE THREAD

**Issue by ghost** [ByteMillennium/spherathon#14]
All you have to do is make it closer together or farther away so the ball can't get stuck.

![bug](https://user-images.githubusercontent.com/25394678/30218203-0a069d56-947e-11e7-967c-da2d3acb146a.png)

**Comment by ArjunMadana** [comment]
Resolved

**Comment by ghost** [comment]
Did you also fix it for the other gap next to it?

**Comment by ArjunMadana** [comment]
I fixed both
