### ISSUE TITLE
Remove white bar at the finish line

### ISSUE THREAD

**Issue by ghost** [ByteMillennium/spherathon#25]
Remove the white bar at the finish line and make the "finish" text be touching the actual sensing y positioning (the wall).

**Comment by ArjunMadana** [comment]
So the player should have to touch the wall to win, right?

**Comment by ghost** [comment]
That already is the case, right? The reason for this issue is because the gets in the way.

**Comment by ArjunMadana** [comment]
They don't have to touch the wall, they just have to go under the "roof" of the finish line, but I understand what you mean

**Comment by ghost** [comment]
Ok, so make it touch the wall and remove the bar.

**Comment by ArjunMadana** [comment]
Resolved
