### ISSUE TITLE
Make rapidly clicking the settings icon not skip the animation

### ISSUE THREAD

**Issue by ghost** [ByteMillennium/spherathon#32]
This can be fixed by just reversing the animation from where it is when you click it. I know how to do this in CSS so maybe there is a way to do this.

**Comment by ArjunMadana** [comment]
@CameronSamuels  I could make it where the settings button brings up a menu, I was planning on doing this anyways because I am going to add more options in the future

**Comment by ghost** [comment]
Sounds good.
