### ISSUE TITLE
Make everything not camel case

### ISSUE THREAD

**Issue by ghost** [ByteMillennium/spherathon#4]
This means to make everything only have a capital at the first letter of the sentences (unless needed).

For example, the shop popup.

**Comment by ArjunMadana** [comment]
Resolved

**Comment by ghost** [comment]
@ArjunMadana, you need to fix this for the quit. But on the quit menu, you should change it to say "Exit the game".

**Comment by ArjunMadana** [comment]
Ok, fixed it
